apiVersion: v1
kind: Service
metadata:
  labels:
    app: actordemo
  name: actordemo
spec:
  clusterIP: None
  ports:
  - port: 9110
    name: petabridge-cmd
  - port: 4053
    name: akka-net
  selector:
    app: actordemo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: actordemo
  labels:
    app: actordemo
spec:
  serviceName: actordemo
  replicas: 2
  selector:
    matchLabels:
      app: actordemo
  template:
    metadata:
      labels:
        app: actordemo
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: actordemo
        #image: gcr.io/cs647-240119/actordemo:v1
        image: actordemo:latest
        # Use Never for local minikube, Always for gcr.io
        imagePullPolicy: Never #Always #Never
        ports:
        - containerPort: 4053
          name: akka-net
        - containerPort: 9110
          name: petabridge-cmd
        resources:
          limits:
            cpu: "500m"
            memory: 256M
          requests:
            cpu: "500m"
            memory: 128M
        env:
          # akka seeds will be actordemo-{n}.$AKKA_SEED_PATH for each n
          - name: AKKA_SEED_PATH
            value: "actordemo.default.svc.cluster.local"
        readinessProbe:
          tcpSocket:
            port: 4053
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: actor-data
          mountPath: /akkadata
  volumeClaimTemplates:
  - metadata:
      name: actor-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
